In [21]:
import pandas as pd

X_train_knn = pd.read_csv("../data/X_train_weather_columns_6.csv", encoding='CP949')
X_test_knn = pd.read_csv("../data/X_test_weather_columns_6.csv", encoding='CP949')
y_train_knn = pd.read_csv("../data/y_train_weather_columns_6.csv", encoding='CP949')
y_test_knn = pd.read_csv("../data/y_test_weather_columns_6.csv", encoding='CP949')

In [22]:
from sklearn.neighbors import KNeighborsRegressor

X_train_knn_6 = X_train_knn.drop(['날짜'], axis=1)
X_test_knn_6 = X_test_knn.drop(['날짜'], axis=1)
y_train_knn_total_sales = y_train_knn[['합계']]
y_train_knn_20m = y_train_knn[['20대 남성 선호도 점수']]
y_train_knn_20f = y_train_knn[['20대 여성 선호도 점수']]
y_train_knn_30m = y_train_knn[['30대 남성 선호도 점수']]
y_train_knn_30f = y_train_knn[['30대 여성 선호도 점수']]
y_train_knn_40m = y_train_knn[['40대 남성 선호도 점수']]
y_train_knn_40f = y_train_knn[['40대 여성 선호도 점수']]
y_train_knn_50m = y_train_knn[['50대 남성 선호도 점수']]
y_train_knn_50f = y_train_knn[['50대 여성 선호도 점수']]
y_train_knn_60m = y_train_knn[['60대 남성 선호도 점수']]
y_train_knn_60f = y_train_knn[['60대 여성 선호도 점수']]
knn_total_sales=KNeighborsRegressor()
knn_20m=KNeighborsRegressor()
knn_20f=KNeighborsRegressor()
knn_30m=KNeighborsRegressor()
knn_30f=KNeighborsRegressor()
knn_40m=KNeighborsRegressor()
knn_40f=KNeighborsRegressor()
knn_50m=KNeighborsRegressor()
knn_50f=KNeighborsRegressor()
knn_60m=KNeighborsRegressor()
knn_60f=KNeighborsRegressor()
knn_total_sales.fit(X_train_knn_6,y_train_knn_total_sales)
knn_total_sales_result=knn_total_sales.predict(X_test_knn_6)
knn_20m.fit(X_train_knn_6,y_train_knn_20m)
knn_20m_result=knn_20m.predict(X_test_knn_6)
knn_20f.fit(X_train_knn_6,y_train_knn_20f)
knn_20f_result=knn_20f.predict(X_test_knn_6)
knn_30m.fit(X_train_knn_6,y_train_knn_30m)
knn_30m_result=knn_30m.predict(X_test_knn_6)
knn_30f.fit(X_train_knn_6,y_train_knn_30f)
knn_30f_result=knn_30f.predict(X_test_knn_6)
knn_40m.fit(X_train_knn_6,y_train_knn_40m)
knn_40m_result=knn_40m.predict(X_test_knn_6)
knn_40f.fit(X_train_knn_6,y_train_knn_40f)
knn_40f_result=knn_40f.predict(X_test_knn_6)
knn_50m.fit(X_train_knn_6,y_train_knn_50m)
knn_50m_result=knn_50m.predict(X_test_knn_6)
knn_50f.fit(X_train_knn_6,y_train_knn_50f)
knn_50f_result=knn_50f.predict(X_test_knn_6)
knn_60m.fit(X_train_knn_6,y_train_knn_60m)
knn_60m_result=knn_60m.predict(X_test_knn_6)
knn_60f.fit(X_train_knn_6,y_train_knn_60f)
knn_60f_result=knn_60f.predict(X_test_knn_6)

In [48]:
import joblib
import pandas as pd
joblib.dump(knn_20m, '../data/knn_20m.pkl')
joblib.dump(knn_20f, '../data/knn_20f.pkl')
joblib.dump(knn_30m, '../data/knn_30m.pkl')
joblib.dump(knn_30f, '../data/knn_30f.pkl')
joblib.dump(knn_40m, '../data/knn_40m.pkl')
joblib.dump(knn_40f, '../data/knn_40f.pkl')
joblib.dump(knn_50m, '../data/knn_50m.pkl')
joblib.dump(knn_50f, '../data/knn_50f.pkl')
joblib.dump(knn_60m, '../data/knn_60m.pkl')
joblib.dump(knn_60f, '../data/knn_60f.pkl')
joblib.dump(knn_total_sales, '../data/knn_total_sales.pkl')
pd.DataFrame(knn_20m_result).rename({0:'20대 남성 선호도 점수'}, axis='columns').to_csv('../data/knn_20m.csv')
pd.DataFrame(knn_20f_result).rename({0:'20대 여성 선호도 점수'}, axis='columns').to_csv('../data/knn_20f.csv')
pd.DataFrame(knn_30m_result).rename({0:'30대 남성 선호도 점수'}, axis='columns').to_csv('../data/knn_30m.csv')
pd.DataFrame(knn_30f_result).rename({0:'30대 여성 선호도 점수'}, axis='columns').to_csv('../data/knn_30f.csv')
pd.DataFrame(knn_40m_result).rename({0:'40대 남성 선호도 점수'}, axis='columns').to_csv('../data/knn_40m.csv')
pd.DataFrame(knn_40f_result).rename({0:'40대 여성 선호도 점수'}, axis='columns').to_csv('../data/knn_40f.csv')
pd.DataFrame(knn_50m_result).rename({0:'50대 남성 선호도 점수'}, axis='columns').to_csv('../data/knn_50m.csv')
pd.DataFrame(knn_50f_result).rename({0:'50대 여성 선호도 점수'}, axis='columns').to_csv('../data/knn_50f.csv')
pd.DataFrame(knn_60m_result).rename({0:'60대 남성 선호도 점수'}, axis='columns').to_csv('../data/knn_60m.csv')
pd.DataFrame(knn_60f_result).rename({0:'60대 여성 선호도 점수'}, axis='columns').to_csv('../data/knn_60f.csv')
pd.DataFrame(knn_total_sales_result).rename({0:'합계'}, axis='columns').to_csv('../data/expect_knn_total_sales.csv')

In [49]:
df_knn_20m = pd.DataFrame(knn_20m_result).rename({0:'20대 남성 선호도 점수'}, axis='columns')
df_knn_20f = pd.DataFrame(knn_20f_result).rename({0:'20대 여성 선호도 점수'}, axis='columns')
df_knn_30m = pd.DataFrame(knn_30m_result).rename({0:'30대 남성 선호도 점수'}, axis='columns')
df_knn_30f = pd.DataFrame(knn_30f_result).rename({0:'30대 여성 선호도 점수'}, axis='columns')
df_knn_40m = pd.DataFrame(knn_40m_result).rename({0:'40대 남성 선호도 점수'}, axis='columns')
df_knn_40f = pd.DataFrame(knn_40f_result).rename({0:'40대 여성 선호도 점수'}, axis='columns')
df_knn_50m = pd.DataFrame(knn_50m_result).rename({0:'50대 남성 선호도 점수'}, axis='columns')
df_knn_50f = pd.DataFrame(knn_50f_result).rename({0:'50대 여성 선호도 점수'}, axis='columns')
df_knn_60m = pd.DataFrame(knn_60m_result).rename({0:'60대 남성 선호도 점수'}, axis='columns')
df_knn_60f = pd.DataFrame(knn_60f_result).rename({0:'60대 여성 선호도 점수'}, axis='columns')
df_knn_total_sales = pd.DataFrame(knn_total_sales_result).rename({0:'합계'}, axis='columns')
expect_knn_score = pd.concat([df_knn_20m, df_knn_20f, df_knn_30m, df_knn_30f, df_knn_40m, df_knn_40f, df_knn_50m, df_knn_50f, df_knn_60m, df_knn_60f], axis=1)

In [50]:
expect_knn_score

,20대 남성 선호도 점수,20대 여성 선호도 점수,30대 남성 선호도 점수,30대 여성 선호도 점수,40대 남성 선호도 점수,40대 여성 선호도 점수,50대 남성 선호도 점수,50대 여성 선호도 점수,60대 남성 선호도 점수,60대 여성 선호도 점수
0,0.125387,0.053919,0.074257,0.073271,0.095819,0.102494,0.092768,0.092900,0.199798,0.089386
1,0.109195,0.075417,0.100552,0.077294,0.098302,0.058088,0.018782,0.116324,0.154620,0.191426
2,0.047341,0.088273,0.085503,0.205924,0.182112,0.089386,0.063926,0.079717,0.081507,0.076310
3,0.116131,0.082289,0.232132,0.083100,0.113454,0.140182,0.061821,0.053599,0.053851,0.063442
4,0.064171,0.199819,0.088694,0.095866,0.070047,0.112141,0.065455,0.094620,0.146344,0.062841
...,...,...,...,...,...,...,...,...,...,...
24111,0.107192,0.153328,0.120847,0.094836,0.110141,0.045748,0.195959,0.069295,0.066741,0.035912
24112,0.086301,0.077658,0.110658,0.186545,0.078455,0.220942,0.068664,0.075944,0.045697,0.049136
24113,0.181732,0.127577,0.089482,0.093447,0.144931,0.092753,0.094711,0.031385,0.095899,0.048083
24114,0.070823,0.061540,0.078617,0.092416,0.162231,0.080948,0.125007,0.080336,0.134239,0.113842
24115,0.135716,0.097839,0.082689,0.127342,0.095626,0.088147,0.051310,0.128374,0.093261,0.099696

In [51]:
from sklearn.metrics import mean_squared_error
import numpy as np
def rmse(y,pred):
    return np.sqrt(mean_squared_error(y,pred))

In [52]:
real_knn_score = y_test_knn[['20대 남성 선호도 점수','20대 여성 선호도 점수','30대 남성 선호도 점수','30대 여성 선호도 점수','40대 남성 선호도 점수','40대 여성 선호도 점수','50대 남성 선호도 점수','50대 여성 선호도 점수','60대 남성 선호도 점수','60대 여성 선호도 점수']]

In [53]:
rmse_knn_score = rmse(real_knn_score,expect_knn_score)

In [54]:
rmse_knn_score

0.13052647913214344

In [55]:
expect_knn_score.to_csv('../data/expect_knn_score.csv')

In [56]:
real_knn_total_sales = y_test_knn[['합계']]

In [57]:
expect_knn_total_sales=df_knn_total_sales

In [58]:
rmse_knn_total_sales = rmse(real_knn_total_sales,expect_knn_total_sales)

In [59]:
rmse_knn_total_sales

381.57309682236513